apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wfs9u68ql-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wfs9u68ql-python 
  name: wfs9u68ql-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wfs9u68ql-python 
